#!/bin/sh

system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then
  # must agree to Xcode license to install Homebrew
  sudo xcodebuild -license accept

  # install homebrew if it's missing
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if ! command -v brew >/dev/null 2>&1; then
    echo "Still can't find brew on path, attempting to fix"
    echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.zshrc
    eval "$(/opt/homebrew/bin/brew shellenv)"
  fi


  # if homebrew install succeeded, install YADM
  if command -v brew >/dev/null 2>&1; then
    # install YADM
    brew install yadm
  fi


  # if yadm install succeeded, clone and bootsrap dotfiles
  if command -v yadm >/dev/null 2>&1; then
    # clone and bootstrap dotfiles
    yadm clone -f --bootstrap "https://github.com/chrislambe/dotfiles.git"
  fi

fi
